version: "2"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node-exercise
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '9990:3306'